# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956b70375237a9dcc178b54a1c2926b99cb0882fc4ea6fef1d6c22652f983a586e70162a7405c381ad010b4852ef7c4c1e5e076992ae2ff536eb2d9ca06a229b

test:
  secret_key_base: fb8cbed816aa05367a0fc924f08fca9637fc5081d7140186f042decb9d9e67eb1bab2225ddb442836231c46a12d57d4263aad2299539569f02a03caee265436d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
